# Generated by Django 5.1.1 on 2024-09-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trade", "0002_alter_usersymbol_user_alter_userbroker_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersymbol",
            name="comment",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="usersymbol",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
