# Generated by Django 5.1.1 on 2024-09-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trade", "0003_alter_usersymbol_comment_alter_usersymbol_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersymbol",
            name="strategy",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="usersymbol",
            name="timeFrame",
            field=models.CharField(max_length=400, null=True),
        ),
    ]
