# Generated by Django 5.1.1 on 2024-10-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trade", "0005_userbroker_currentreserve"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersymbol",
            name="comment",
            field=models.TextField(default="", null=True),
        ),
    ]
