# Generated by Django 5.1.1 on 2024-10-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trade", "0006_alter_usersymbol_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersymbol",
            name="comment",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="usersymbol",
            name="picture",
            field=models.CharField(blank=True, default="", max_length=500, null=True),
        ),
    ]
