# Generated by Django 5.1.1 on 2024-10-16 22:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trade", "0008_alter_usersymbol_result_alter_usersymbol_riskreward_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userbroker",
            name="availableBalance",
            field=models.DecimalField(decimal_places=4, default=200.0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="broker",
            name="defaultCommission",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0.0"), max_digits=15
            ),
        ),
        migrations.AlterField(
            model_name="symbol",
            name="commission",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0.0"), max_digits=15
            ),
        ),
        migrations.AlterField(
            model_name="userbroker",
            name="balance",
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name="userbroker",
            name="currentReserve",
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name="userbroker",
            name="reserve",
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name="userbroker",
            name="riskPercent",
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name="usersymbol",
            name="amount",
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name="usersymbol",
            name="entry",
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name="usersymbol",
            name="riskReward",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("1.0"), max_digits=15
            ),
        ),
        migrations.AlterField(
            model_name="usersymbol",
            name="stop",
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name="usersymbol",
            name="target",
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
    ]
