# Generated by Django 5.1.1 on 2024-10-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trade", "0009_userbroker_availablebalance_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userbroker",
            old_name="reserve",
            new_name="definedReserve",
        ),
        migrations.AddField(
            model_name="userbroker",
            name="reservePercent",
            field=models.DecimalField(decimal_places=4, default=10.0, max_digits=15),
        ),
    ]
