# Generated by Django 5.1.1 on 2024-10-28 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trade", "0010_rename_reserve_userbroker_definedreserve_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userbroker",
            old_name="currentReserve",
            new_name="reserve",
        ),
        migrations.RemoveField(
            model_name="userbroker",
            name="availableBalance",
        ),
        migrations.RemoveField(
            model_name="userbroker",
            name="definedReserve",
        ),
    ]
