# Generated by Django 5.1.1 on 2024-10-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trade", "0011_rename_currentreserve_userbroker_reserve_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersymbol",
            name="date_ended",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
