# Generated by Django 5.1.1 on 2024-12-11 17:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trade", "0012_usersymbol_date_ended"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserSymbol",
            new_name="Trade",
        ),
        migrations.AlterModelTable(
            name="trade",
            table="trade_usersymbol",
        ),
    ]
