# Generated by Django 5.1.1 on 2024-12-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trade", "0013_rename_usersymbol_trade_alter_trade_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="broker",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="symbol",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="trade",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="userbroker",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
