# Generated by Django 5.1.1 on 2024-12-13 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trade", "0014_alter_broker_id_alter_symbol_id_alter_trade_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trade",
            name="riskReward",
        ),
        migrations.RemoveField(
            model_name="trade",
            name="user",
        ),
        migrations.AddField(
            model_name="trade",
            name="result_amount",
            field=models.DecimalField(
                blank=True, decimal_places=4, default=None, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="ub",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="trade.userbroker",
            ),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name="trade",
            table="trade_usersbrokersymbol",
        ),
    ]
