# Generated by Django 5.1.1 on 2024-12-27 16:00

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trade", "0015_remove_trade_riskreward_remove_trade_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userbroker",
            name="balance",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("2000"), max_digits=15
            ),
        ),
        migrations.AlterField(
            model_name="userbroker",
            name="broker",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="trade.broker",
            ),
        ),
        migrations.AlterField(
            model_name="userbroker",
            name="reserve",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("1800"), max_digits=15
            ),
        ),
        migrations.AlterField(
            model_name="userbroker",
            name="riskPercent",
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=15),
        ),
    ]
