# Generated by Django 5.1.4 on 2025-02-12 03:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trade", "0016_alter_userbroker_balance_alter_userbroker_broker_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trade",
            name="risk_reward",
            field=models.DecimalField(
                blank=True, decimal_places=4, default=None, max_digits=25, null=True
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="stop_percent",
            field=models.DecimalField(
                blank=True, decimal_places=4, default=None, max_digits=25, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="amount",
            field=models.DecimalField(decimal_places=4, max_digits=25),
        ),
        migrations.AlterField(
            model_name="trade",
            name="entry",
            field=models.DecimalField(decimal_places=4, max_digits=25),
        ),
        migrations.AlterField(
            model_name="trade",
            name="result_amount",
            field=models.DecimalField(
                blank=True, decimal_places=4, default=None, max_digits=25, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="stop",
            field=models.DecimalField(decimal_places=4, max_digits=25),
        ),
        migrations.AlterField(
            model_name="trade",
            name="target",
            field=models.DecimalField(decimal_places=4, max_digits=25),
        ),
        migrations.AlterField(
            model_name="userbroker",
            name="balance",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0"), max_digits=15
            ),
        ),
        migrations.AlterField(
            model_name="userbroker",
            name="reserve",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0"), max_digits=15
            ),
        ),
        migrations.AlterField(
            model_name="userbroker",
            name="reservePercent",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0"), max_digits=15
            ),
        ),
        migrations.AlterField(
            model_name="userbroker",
            name="riskPercent",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0"), max_digits=15
            ),
        ),
    ]
