# Generated by Django 5.1.4 on 2025-02-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trade", "0017_trade_risk_reward_trade_stop_percent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trade",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=25, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="entry",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=25, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="stop",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=25, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="target",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=25, null=True
            ),
        ),
    ]
