# Generated by Django 5.1.4 on 2025-03-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trade", "0018_alter_trade_amount_alter_trade_entry_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="symbol",
            name="commission",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=15, null=True
            ),
        ),
    ]
